name: mdm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - chumpy=0.70  # Moved to conda as requested
  - pip
  - pip:
    # Core DL & Geometry
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch==2.9.1+cu128
    - torchvision==0.24.1+cu128
    - numpy==2.2.6
    - scipy==1.15.2
    - scikit-learn==1.7.2
    - matplotlib==3.10.7
    - h5py==3.15.1
    - trimesh==4.10.0
    - smplx==0.1.28
    - pyrender==0.1.45
    
    # Utilities & IO
    - gdown==5.2.0
    - tqdm==4.67.1
    - wandb==0.23.0
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - opencv-python==4.12.0.88
    - moviepy==2.2.1
    - imageio-ffmpeg==0.6.0
    - tensorboard==2.20.0
    - pillow==11.3.0

    # NLP & Diffusion
    - spacy==3.8.11
    # Direct URL allows automatic installation of the spacy model:
    - en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl
    - openai-clip==1.0.1
    - diffusers==0.30.2
    - einops==0.8.1
    - blis==1.3.3